AWSTemplateFormatVersion: "2010-09-09"
Description: Deployment of a highly available LAMP stack
Parameters:

  VpcId:
    Type: String
  Subnets:
    Type: CommaDelimitedList
  NodeCount:
    Type: String
  KeyName:
    Type: String
  ImageId:
    Type: String
  AccessIp:
    Type: String

Resources:

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Scheme: internet-facing
      SecurityGroups: 
        - Ref: SecurityGroup
      Subnets: 
        Ref: Subnets
      Tags: 
        - Key: Name
          Value: 
            Fn::Sub: "${AWS::StackName}-LoadBalancer"
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Tags: 
        - Key: Name
          Value: 
            Fn::Sub: "${AWS::StackName}-TargetGroup"
      VpcId: 
        Ref: VpcId

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: True
    Properties: 
      DesiredCapacity: 
        Ref: NodeCount
      HealthCheckGracePeriod: 30
      HealthCheckType: EC2
      LaunchConfigurationName: 
        Ref: LaunchConfiguration
      MaxSize: 
        Ref: NodeCount
      MinSize: 
        Ref: NodeCount
      Tags: 
        - Key: Name
          Value: 
            Fn::Sub: "${AWS::StackName}-AutoScalingGroup"
          PropagateAtLaunch: True
      TargetGroupARNs: 
        - Ref: TargetGroup
      VPCZoneIdentifier: 
        Ref: Subnets

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      IamInstanceProfile: 
        Ref: IamProfile
      ImageId: 
        Ref: ImageId
      InstanceType: t2.small
      KeyName: 
        Ref: KeyName
      SecurityGroups: 
        - Ref: SecurityGroup
      UserData: 
        Fn::Base64: 
          Fn::Sub: |
            #!/usr/bin/env bash

            # cfn-signal --region ${AWS::Region} --stack ${AWS::StackName} --resource AutoScalingGroup --exit-code 0

            echo "Test" > /tmp/output.txt

            # Initial Config

            sudo apt update -y

            # Set Variables

            appname="application"

            # Install

            sudo apt install apache2 -y
            sudo mkdir /var/www/application
            sudo apt-get install python3.6 -y
            sudo apt install python3-pip -y
            mkdir /opt/$appname
            python3 -m pip install boto3 -t /opt/$appname/
            python3 -m pip install flask -t /opt/$appname/
            sudo apt-get install libapache2-mod-wsgi -y

            # Configure

            echo "<h1>$appname</h1>" > /var/www/html/index.html
            echo "<a href='/app'><p>Application Link</p></a>" >> /var/www/html/index.html

            ## Application File
            echo '

            #!/usr/bin/python3

            import sys
            import os
            import random

            sys.path.append(os.path.dirname(__file__))

            import boto3
            from flask import Flask

            app = Flask(__name__)

            @app.route("/")

            def hello():
                dynamodb = boto3.resource("dynamodb",  region_name="ap-southeast-2")
                table = dynamodb.Table("${AWS::StackName}-DynamoDBTable")
                table.put_item(
                    Item={
                        "ID": str(random.randint(0, 1000)),
                        "User": "John"
                    }
                )
                client = boto3.client("dynamodb",  region_name="ap-southeast-2")
                response = len(client.scan(TableName="${AWS::StackName}-DynamoDBTable")["Items"])
                return "The number of rows in the table is " + str(response)

            def application(environ, start_response):
                status = "200 OK"
                html = hello()
                response_header = [("Content-type","text/html")]
                start_response(status,response_header)
                return [html]

            if __name__ == "__main__":
                print(hello())

            ' > /opt/$appname/app.py

            echo "
            <VirtualHost *:80>
                 ServerAlias \"*\"
                 # Give an alias to to start your website url with
                 WSGIScriptAlias /app /opt/$appname/app.py
                 <Directory /opt/$appname/>
                    # set permissions as per apache2.conf file
                        Options FollowSymLinks
                        AllowOverride None
                        Require all granted
                 </Directory>
                 ErrorLog ${!APACHE_LOG_DIR}/error.log
                 LogLevel warn
                 CustomLog ${!APACHE_LOG_DIR}/access.log combined
            </VirtualHost>
            " > /etc/apache2/sites-available/$appname.conf

            sudo a2ensite $appname.conf

            service apache2 restart

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: 
        Fn::Sub: "${AWS::StackName} Security Group"
      GroupName: 
        Fn::Sub: "${AWS::StackName}-SecurityGroup"
      SecurityGroupEgress: 
        - CidrIp: 
            Ref: AccessIp
          FromPort: 0
          IpProtocol: tcp
          ToPort: 65535
        - CidrIp: 0.0.0.0/0
          FromPort: 0
          IpProtocol: tcp
          ToPort: 65535
      SecurityGroupIngress: 
        - CidrIp: 
            Ref: AccessIp
          FromPort: 0
          IpProtocol: tcp
          ToPort: 65535
      Tags: 
        - Key: Name
          Value: 
            Fn::Sub: "${AWS::StackName}-SecurityGroup"
      VpcId: 
        Ref: VpcId

  IamProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: 
        Fn::Sub: "${AWS::StackName}-IamProfile"
      Roles: 
        - Ref: IamRole

  IamRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns: 
        - Ref: IamPolicy
      RoleName: 
        Fn::Sub: "${AWS::StackName}-IamRole"
      Tags: 
        - Key: Name
          Value: 
            Fn::Sub: "${AWS::StackName}-IamRole"

  IamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      ManagedPolicyName: 
        Fn::Sub: "${AWS::StackName}-IamPolicy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
        - Effect: "Allow"
          Action: "ec2:Read*"
          Resource:
            Fn::Sub: "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:*"
        - Effect: "Allow"
          Action: 
            - "dynamodb:BatchGetItem"
            - "dynamodb:ConditionCheckItem"
            - "dynamodb:PutItem"
            - "dynamodb:Scan"
            - "dynamodb:ListTagsOfResource"
            - "dynamodb:Query"
            - "dynamodb:DescribeStream"
            - "dynamodb:UpdateItem"
            - "dynamodb:DescribeTimeToLive"
            - "dynamodb:ListStreams"
            - "dynamodb:DescribeGlobalTableSettings"
            - "dynamodb:DescribeReservedCapacityOfferings"
            - "dynamodb:DescribeTable"
            - "dynamodb:GetShardIterator"
            - "dynamodb:DescribeGlobalTable"
            - "dynamodb:DescribeReservedCapacity"
            - "dynamodb:GetItem"
            - "ec2:Read*"
            - "dynamodb:DescribeContinuousBackups"
            - "dynamodb:DescribeBackup"
            - "dynamodb:DescribeLimits"
            - "dynamodb:GetRecords"
          Resource: "*"

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: ID
          AttributeType: S
        - AttributeName: User
          AttributeType: S
      BillingMode: PAY_PER_REQUEST 
      KeySchema: 
        - AttributeName: ID
          KeyType: HASH
        - AttributeName: User
          KeyType: RANGE
      TableName: 
        Fn::Sub: "${AWS::StackName}-DynamoDBTable"
      Tags: 
        - Key: Name
          Value: 
            Fn::Sub: "${AWS::StackName}-DynamoDBTable"